#!/usr/bin/env

set -e

convox login ${CONVOX_GRID_HOST} -p ${CONVOX_API_KEY}
convox switch ${1}
convox env set CONNECTION_HOST=${1}_${CONNECTION_HOST} CONNECTION_USER=${1}_${CONNECTION_USER} CONNECTION_PASSWORD=${1}_${CONNECTION_PASSWORD} CONNECTION_DB=${1}_${CONNECTION_DB} CONNECTION_POOL=${1}_${CONNECTION_POOL} CENSUS_DATA=${1}_${CENSUS_DATA} VOTES_DATA=${1}_${VOTES_DATA} INFO_DATA=${1}_${INFO_DATA} DEMOGRAPHIC_CACHE=${1}_${DEMOGRAPHIC_CACHE}
convox deploy
