#!/usr/bin/env

set -e

convox login -h ${CONVOX_GRID_HOST} -p ${CONVOX_API_KEY}
convox switch ${1}
convox env set CONNECTION_HOST=${CONNECTION_HOST} CONNECTION_USER=${CONNECTION_APP} CONNECTION_PASSWORD=${CONNECTION_PASSWORD} CONNECTION_DB=${CONNECTION_DB} CONNECTION_POOL=${CONNECTION_POOL} CENSUS_DATA=${CENSUS_DATA} VOTES_DATA=${VOTES_DATA} INFO_DATA=${INFO_DATA} DEMOGRAPHIC_CACHE=${DEMOGRAPHIC_CACHE}
convox deploy
