#!/usr/bin/env

set -e

convox login ${CONVOX_GRID_HOST} -p ${CONVOX_API_KEY}
convox switch ${1}
convox env set CONNECTION_HOST=${1}_CONNECTION_HOST CONNECTION_USER=${1}_CONNECTION_USER CONNECTION_PASSWORD=${1}_CONNECTION_PASSWORD CONNECTION_DB=${1}_CONNECTION_DB CONNECTION_POOL=${1}_CONNECTION_POOL CENSUS_DATA=${1}_CENSUS_DATA VOTES_DATA=${1}_VOTES_DATA INFO_DATA=${1}_INFO_DATA DEMOGRAPHIC_CACHE=${1}_DEMOGRAPHIC_CACHE
convox deploy
